-- MySQL Script generated by MySQL Workbench
-- Sun Feb 18 14:59:56 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ebagshare
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ebagshare
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ebagshare` DEFAULT CHARACTER SET utf8 ;
USE `ebagshare` ;


DROP TABLE T_ARTICLE;
DROP TABLE T_ARTICLE_HISTORY;
DROP TABLE T_AVIS;
DROP TABLE T_AVIS_HISTORY;
DROP TABLE T_OFFRE;
DROP TABLE T_OFFRE_HISTORY;
DROP TABLE T_PRECISION;
DROP TABLE T_PRECISION_HISTORY;
DROP TABLE T_RESERVER;
DROP TABLE T_RESERVER_HISTORY;
DROP TABLE T_TYPE_ARTICLE;
DROP TABLE T_TYPE_ARTICLE_HISTORY;
DROP TABLE T_USER;
DROP TABLE T_USER_HISTORY;


-- -----------------------------------------------------
-- Table `ebagshare`.`T_USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebagshare`.`T_USER` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_inscri` DATETIME NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `tel` VARCHAR(45) NOT NULL,
  `adresse` VARCHAR(150) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `est_confirmee` CHAR(1) NOT NULL DEFAULT 'N',
  `date_modif` DATETIME NOT NULL,
  `ip_adress` VARCHAR(45) NOT NULL,
  `identite` VARCHAR(45) NOT NULL,
  `identite_confirme` CHAR(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebagshare`.`T_OFFRE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebagshare`.`T_OFFRE` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `date_ajout` DATETIME NOT NULL,
  `date_modif` DATETIME NOT NULL,
  `nb_kg_dispo` INT NOT NULL,
  `nb_env_dispo` INT NOT NULL,
  `ville_depart` VARCHAR(45) NOT NULL,
  `ville_arrivee` VARCHAR(45) NOT NULL,
  `date_depart` DATETIME NOT NULL,
  `date_arrivee` DATETIME NOT NULL,
  `prix_kg` INT NOT NULL,
  `prix_env` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_idx` (`id_user` ASC),
  CONSTRAINT `useroffre`
    FOREIGN KEY (`id_user`)
    REFERENCES `ebagshare`.`T_USER` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebagshare`.`T_PRESICION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebagshare`.`T_PRECISION` (
  `id` INT AUTO_INCREMENT, -- (solofo) rajout id => on aura plusieur precision pour une offre
  `id_offre` INT NOT NULL,
  `numero_vol` VARCHAR(45) NOT NULL,
  `dimensionL` INT NOT NULL,
  `dimensionH` INT NOT NULL,
  `nom_company` VARCHAR(45) NOT NULL,
  `detail` VARCHAR(200) NULL,
  PRIMARY KEY (`id`),   -- (solofo) id comme cle primaire       
  CONSTRAINT `id_offrepress`
    FOREIGN KEY (`id_offre`)
    REFERENCES `ebagshare`.`T_OFFRE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebagshare`.`T_AVIS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebagshare`.`T_AVIS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `note` INT NOT NULL,
  `texte` VARCHAR(200) NOT NULL,
  `id_user` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_idx` (`id_user` ASC),
  CONSTRAINT `useravis`
    FOREIGN KEY (`id_user`)
    REFERENCES `ebagshare`.`T_USER` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebagshare`.`T_RESERVER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebagshare`.`T_RESERVER` (
  `id_offre` INT NOT NULL,
  `id_user` INT NOT NULL,
  `nb_kg` INT NOT NULL DEFAULT 0,
  `nb_env` INT NOT NULL DEFAULT 0,
  `id_avis_v` INT NOT NULL,
  `id_avis_c` INT NOT NULL,
  `date_reservation` DATETIME NOT NULL,
  `est_confirme` CHAR(1) NULL DEFAULT 'N',
  PRIMARY KEY (`id_offre`, `id_user`),
  INDEX `user_idx` (`id_user` ASC),
  INDEX `avic_v_idx` (`id_avis_v` ASC),
  INDEX `avic_c_idx` (`id_avis_c` ASC),
  CONSTRAINT `offreRes`
    FOREIGN KEY (`id_offre`)
    REFERENCES `ebagshare`.`T_OFFRE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `userRes`
    FOREIGN KEY (`id_user`)
    REFERENCES `ebagshare`.`T_USER` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `avic_vRes`
    FOREIGN KEY (`id_avis_v`)
    REFERENCES `ebagshare`.`T_AVIS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `avic_cRes`
    FOREIGN KEY (`id_avis_c`)
    REFERENCES `ebagshare`.`T_AVIS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebagshare`.`T_TYPE_ARTICLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebagshare`.`T_TYPE_ARTICLE` (
  `id_article` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_article`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebagshare`.`T_ARTICLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebagshare`.`T_ARTICLE` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_reservation` INT NOT NULL,
  `id_user` INT NOT NULL,
  `type` INT NOT NULL,
  `marque` VARCHAR(45) NOT NULL,
  `valeur` CHAR(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (`id`, `id_user`, `id_reservation`),
  INDEX `id_reservation_idx` (`id_reservation` ASC),
  INDEX `id_user_idx` (`id_user` ASC),
  INDEX `typearticle_idx` (`type` ASC),
  CONSTRAINT `id_reservation`
    FOREIGN KEY (`id_reservation`)
    REFERENCES `ebagshare`.`T_RESERVER` (`id_offre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `ebagshare`.`T_RESERVER` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `typearticle`
    FOREIGN KEY (`type`)
    REFERENCES `ebagshare`.`T_TYPE_ARTICLE` (`id_article`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebagshare`.`T_AVIS_HISTORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebagshare`.`T_AVIS_HISTORY` (
  `id` INT AUTO_INCREMENT, -- (solofo) avis modifié plusieurs fois
  `id_avis` INT NOT NULL,
  `note` INT NOT NULL,
  `texte` VARCHAR(200) NOT NULL,
  `id_user` INT NULL,
  `date_modif` DATETIME,
  PRIMARY KEY (`id`),
  CONSTRAINT `avisH`
    FOREIGN KEY (`id_avis`)
    REFERENCES `ebagshare`.`T_AVIS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebagshare`.`T_PRESICION_HISTORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebagshare`.`T_PRECISION_HISTORY` (
  `id` INT AUTO_INCREMENT,
  `id_precision` INT NOT NULL,
  `id_offre` INT NOT NULL,
  `numero_vol` VARCHAR(45) NOT NULL,
  `dimensionL` INT NOT NULL,
  `dimensionH` INT NOT NULL,
  `nom_company` VARCHAR(45) NOT NULL,
  `detail` VARCHAR(200) NULL,
  `date_modif` DATETIME,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`id_offre`) REFERENCES `T_OFFRE`(`id`),
  CONSTRAINT `presH`
    FOREIGN KEY (`id_precision`)
    REFERENCES `ebagshare`.`T_PRECISION` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebagshare`.`T_RESERVER_HISTORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebagshare`.`T_RESERVER_HISTORY` (
  `id` INT AUTO_INCREMENT,
  `id_offre` INT NOT NULL,
  `id_user` INT NOT NULL,
  `nb_kg` INT NOT NULL DEFAULT 0,
  `nb_env` INT NOT NULL DEFAULT 0,
  `id_avis_v` INT NOT NULL,
  `id_avis_c` INT NOT NULL,
  `date_reservation` DATETIME NOT NULL,
  `est_confirme` CHAR(1) NULL DEFAULT 'N',
  `date_modif` DATETIME,
  PRIMARY KEY (`id`),
  CONSTRAINT `reservh`
    FOREIGN KEY (`id_offre` , `id_user`)
    REFERENCES `ebagshare`.`T_RESERVER` (`id_offre` , `id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebagshare`.`T_TYPE_ARTICLE_HISTORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebagshare`.`T_TYPE_ARTICLE_HISTORY` (
  `id` INT AUTO_INCREMENT,
  `id_article` INT NOT NULL,
  `type` VARCHAR(50) NOT NULL,
  `date_modif` DATETIME,
  PRIMARY KEY (`id`),
  CONSTRAINT `typeh`
    FOREIGN KEY (`id_article`)
    REFERENCES `ebagshare`.`T_TYPE_ARTICLE` (`id_article`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebagshare`.`T_USER_HISTORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebagshare`.`T_USER_HISTORY` (
  `id` INT AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `date_inscri` DATETIME NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `tel` VARCHAR(45) NOT NULL,
  `adresse` VARCHAR(150) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `est_confirmee` CHAR(1) NOT NULL DEFAULT 'N',
  `date_modif` DATETIME NOT NULL,
  `ip_adress` VARCHAR(45) NOT NULL,
  `identite` VARCHAR(45) NOT NULL,
  `identite_confirme` CHAR(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (`id`),
  CONSTRAINT `userh`
    FOREIGN KEY (`id_user`)
    REFERENCES `ebagshare`.`T_USER` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebagshare`.`T_OFFRE_HISTORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebagshare`.`T_OFFRE_HISTORY` (
  `id` INT AUTO_INCREMENT,
  `id_offre` INT NOT NULL,
  `id_user` INT NOT NULL,
  `date_ajout` DATETIME NOT NULL,
  `date_modif` DATETIME NOT NULL,
  `nb_kg_dispo` INT NOT NULL,
  `nb_env_dispo` INT NOT NULL,
  `ville_depart` VARCHAR(45) NOT NULL,
  `ville_arrivee` VARCHAR(45) NOT NULL,
  `date_depart` DATETIME NOT NULL,
  `date_arrivee` DATETIME NOT NULL,
  `prix_kg` INT NOT NULL,
  `prix_env` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `OffreH`
    FOREIGN KEY (`id_offre`)
    REFERENCES `ebagshare`.`T_OFFRE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebagshare`.`T_ARTICLE_HISTORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebagshare`.`T_ARTICLE_HISTORY` (
  `id` INT AUTO_INCREMENT,
  `id_article` INT NOT NULL,
  `id_reservation` INT NOT NULL,
  `id_user` INT NOT NULL,
  `type` INT NOT NULL,
  `marque` VARCHAR(45) NOT NULL,
  `valeur` CHAR(1) NOT NULL DEFAULT 'N',
  `date_modif` DATETIME,
  PRIMARY KEY (`id`),
  INDEX `articleH2_idx` (`id_reservation` ASC),
  CONSTRAINT `articleH`
    FOREIGN KEY (`id_article`)
    REFERENCES `ebagshare`.`T_ARTICLE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `articleH2`
    FOREIGN KEY (`id_reservation`)
    REFERENCES `ebagshare`.`T_ARTICLE` (`id_reservation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `ebagshare`.`T_USER`
-- -----------------------------------------------------
START TRANSACTION;
USE `ebagshare`;
INSERT INTO `ebagshare`.`T_USER` (`id`, `date_inscri`, `nom`, `prenom`, `mail`, `tel`, `adresse`, `login`, `password`, `est_confirmee`, `date_modif`, `ip_adress`, `identite`, `identite_confirme`) VALUES (1, '2018-02-17 15:22:32', 'Trabelsi', 'Ousseama', 'troussemaa@gmail.com', '0711001100', '33 allee chantegrillet 42000', 'oussema', 'oussema', 'O', '2018-02-07 15:22:32', '192.0.0.0.1', 'url vers id', 'N');
INSERT INTO `ebagshare`.`T_USER` (`id`, `date_inscri`, `nom`, `prenom`, `mail`, `tel`, `adresse`, `login`, `password`, `est_confirmee`, `date_modif`, `ip_adress`, `identite`, `identite_confirme`) VALUES (2, '2018-01-15 17:02:32', 'Solo', 'Solo', 'Solo@gmail.com', '17', 'saint etienne', 'solo', 'solo', 'N', '2018-02-07 08:22:15', '192.1.3.2.5', 'url vers passport', 'N');

COMMIT;


-- -----------------------------------------------------
-- Data for table `ebagshare`.`T_OFFRE`
-- -----------------------------------------------------
START TRANSACTION;
USE `ebagshare`;
INSERT INTO `ebagshare`.`T_OFFRE` (`id`, `id_user`, `date_ajout`, `date_modif`, `nb_kg_dispo`, `nb_env_dispo`, `ville_depart`, `ville_arrivee`, `date_depart`, `date_arrivee`, `prix_kg`, `prix_env`) VALUES (1, 1, '2018-02-18 09:50:50', '2018-02-18 09:55:50', 20, 15, 'Paris', 'Tunis', '2018-02-25 07:00:00', '2018-02-25 09:00:00', 5, 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `ebagshare`.`T_PRECISION`
-- -----------------------------------------------------
START TRANSACTION;
USE `ebagshare`;
INSERT INTO `ebagshare`.`T_PRECISION` (`id_offre`, `numero_vol`, `dimensionL`, `dimensionH`, `nom_company`, `Detail`) VALUES (1, 'TU263', 20, 30, 'TunisAir', 'pas alcool svp. (habib)');

COMMIT;


-- -----------------------------------------------------
-- Data for table `ebagshare`.`T_AVIS`
-- -----------------------------------------------------
START TRANSACTION;
USE `ebagshare`;
INSERT INTO `ebagshare`.`T_AVIS` (`id`, `note`, `texte`, `id_user`) VALUES (1, 9, 'bien', 2);
INSERT INTO `ebagshare`.`T_AVIS` (`id`, `note`, `texte`, `id_user`) VALUES (2, 8, 'bien bien', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `ebagshare`.`T_RESERVER`
-- -----------------------------------------------------
START TRANSACTION;
USE `ebagshare`;
INSERT INTO `ebagshare`.`T_RESERVER` (`id_offre`, `id_user`, `nb_kg`, `nb_env`, `id_avis_v`, `id_avis_c`, `date_reservation`, `est_confirme`) VALUES (1, 2, 10, 0, 1, 2, '2018-02-18 12:00:23', 'N');

COMMIT;


-- -----------------------------------------------------
-- Data for table `ebagshare`.`T_TYPE_ARTICLE`
-- -----------------------------------------------------
START TRANSACTION;
USE `ebagshare`;
INSERT INTO `ebagshare`.`T_TYPE_ARTICLE` (`id_article`, `type`) VALUES (1, 'Vetements');
INSERT INTO `ebagshare`.`T_TYPE_ARTICLE` (`id_article`, `type`) VALUES (2, 'Makeup');
INSERT INTO `ebagshare`.`T_TYPE_ARTICLE` (`id_article`, `type`) VALUES (3, 'Bijoux');
INSERT INTO `ebagshare`.`T_TYPE_ARTICLE` (`id_article`, `type`) VALUES (4, 'Electromenager');

COMMIT;


-- -----------------------------------------------------
-- Data for table `ebagshare`.`T_ARTICLE`
-- -----------------------------------------------------
START TRANSACTION;
USE `ebagshare`;
INSERT INTO `ebagshare`.`T_ARTICLE` (`id`, `id_reservation`, `id_user`, `type`, `marque`, `valeur`) VALUES (1, 1, 2, 1, 'Nike', 'O');
INSERT INTO `ebagshare`.`T_ARTICLE` (`id`, `id_reservation`, `id_user`, `type`, `marque`, `valeur`) VALUES (2, 1, 2, 2, 'Dior', 'N');

COMMIT;

